// app/vault/page.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

export default function TheVault() {
  const [template, setTemplate] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const saved = localStorage.getItem("rosewood_discovered_blueprint");
    if (saved) {
      try {
        setTemplate(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse custom template from storage", e);
      }
    }
    setLoading(false);
  }, []);

  const getCategoryName = (scope: string) => {
    const s = scope ? scope.toLowerCase() : "";
    if (s === "deals" || s === "deal" || s === "leads" || s === "lead") return "Deals";
    if (s === "people" || s === "person" || s === "contacts") return "Person";
    if (s === "organizations" || s === "organization" || s === "org") return "Organizations";
    if (s === "products" || s === "product") return "Products";
    if (s === "projects" || s === "project") return "Projects";
    return "Deals"; // Fallback default
  };

  const handleExportMarkdown = () => {
    if (!template) return;
    
    let md = `# Rosewood CRM Implementation Playbook\n\n`;
    md += `> **Generated On:** ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    md += `> **System Configuration:** Rosewood CRM Engine IaC Platform\n\n`;
    
    md += `## 1. Executive Summary\n\n`;
    md += `| Attribute | Configuration Detail |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Template Name** | ${template.name || "Unnamed Template"} |\n`;
    md += `| **Version** | ${template.version || "1.0.0"} |\n`;
    md += `| **Pipeline Channels** | ${template.pipelines?.length || 0} active channels |\n`;
    md += `| **Custom Fields** | ${template.customFields?.length || 0} fields configured |\n\n`;
    
    md += `## 2. Operational Standard Operating Procedure (SOP) Guide\n\n`;
    if (template.pipelines && template.pipelines.length > 0) {
      template.pipelines.forEach((pipe: any, index: number) => {
        md += `### 2.${index + 1} Pipeline: ${pipe.name}\n\n`;
        md += `Below is the ordered sequence of stages required to guide entities through the **${pipe.name}** lifecycle. Ensure operational teams adhere to the stagnation criteria defined below.\n\n`;
        
        (pipe.stages || []).forEach((stage: any, sIndex: number) => {
          const days = stage.rottenDays !== undefined ? stage.rottenDays : stage.rotten_days;
          md += `#### Stage ${sIndex + 1}: ${stage.name}\n`;
          if (days !== null && days !== undefined && days !== "") {
            md += `- **Operational Rule**: 🚨 *CRITICAL TIMELINE: Object must progress within ${days} days or it triggers an operational stagnation alert.*\n\n`;
          } else {
            md += `- **Operational Rule**: ✓ *Continuous Nurture Step (No expiration decay criteria assigned).*\n\n`;
          }
        });
      });
    } else {
      md += `*No active pipelines configured in this template setup.*\n\n`;
    }
    
    md += `## 3. Data Dictionary Index & Deployment Checklist\n\n`;
    md += `All custom fields defined below must be provisioned in the target CRM environment. Use the checklist columns to monitor compliance and configuration status.\n\n`;
    
    const categories = ["Deals", "Person", "Organizations", "Products", "Projects"];
    categories.forEach(cat => {
      md += `### ${cat} Fields Checklist\n\n`;
      const fields = (template.customFields || []).filter((f: any) => getCategoryName(f.scope) === cat);
      
      if (fields.length > 0) {
        md += `| Provision | Field Name | Data Type | Scope | Configuration Key |\n`;
        md += `| :---: | :--- | :--- | :--- | :--- |\n`;
        fields.forEach((f: any) => {
          md += `| [ ] | ${f.name} | \`${f.type || "text"}\` | ${cat} | \`${f.id}\` |\n`;
        });
        md += `\n`;
      } else {
        md += `*No custom fields configured for the ${cat} context.*\n\n`;
      }
    });
    
    md += `\n---\n*End of Playbook. Generated by Rosewood CRM Engine.*`;

    // Trigger client-side browser download
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `rosewood-crm-playbook.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px] text-slate-500 dark:text-zinc-400">
        <svg className="animate-spin h-6 w-6 text-slate-400 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        <span>Loading dynamic playbook data...</span>
      </div>
    );
  }

  // Fallback empty state styled beautifully according to Material Expressive guidelines
  if (!template) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">
        <div className="bg-white dark:bg-zinc-900 border border-slate-200/90 dark:border-zinc-800 rounded-2xl p-10 shadow-sm text-center space-y-6 transition-all duration-200">
          <div className="h-16 w-16 bg-slate-50 dark:bg-zinc-950 rounded-full flex items-center justify-center mx-auto border border-slate-200/50 dark:border-zinc-800/80">
            <span className="text-3xl">🗃️</span>
          </div>
          <div className="space-y-2 max-w-lg mx-auto">
            <h2 className="text-xl font-bold text-slate-800 dark:text-zinc-100">
              No Active Workspace Setup Detected
            </h2>
            <p className="text-sm text-slate-500 dark:text-zinc-400 leading-relaxed">
              Establish a connection handshake or configure a template in the Feature Studio to compile documentation.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 pt-2">
            <Link 
              href="/" 
              className="bg-slate-900 hover:bg-slate-800 text-white dark:bg-zinc-100 dark:hover:bg-zinc-200 dark:text-zinc-950 font-semibold px-5 py-2.5 rounded-xl text-xs uppercase tracking-wider shadow-sm transition-all duration-150 active:scale-[0.98]"
            >
              🚀 Launchpad
            </Link>
            <Link 
              href="/studio" 
              className="bg-white dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 text-slate-700 dark:text-zinc-200 hover:bg-slate-50 dark:hover:bg-zinc-700/60 font-semibold px-5 py-2.5 rounded-xl text-xs uppercase tracking-wider shadow-sm transition-all duration-150 active:scale-[0.98]"
            >
              🎨 Feature Studio
            </Link>
          </div>
        </div>
      </div>
    );
  }

  const customFieldsCount = template.customFields?.length || 0;
  const categoriesList = ["Deals", "Person", "Organizations", "Products", "Projects"];

  return (
    <div className="max-w-7xl mx-auto px-2 md:px-4 py-2 space-y-8 animate-fade-in">
      
      {/* Immersive adaptive Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 dark:border-zinc-800/80 pb-6 transition-colors duration-200">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 dark:text-zinc-100 font-sans">
            The Vault
          </h1>
          <p className="text-slate-500 dark:text-zinc-400 text-sm mt-1.5 max-w-2xl leading-relaxed">
            Auto-generated internal operational SOP recipes and customer sales manuals compiled directly from the active template configuration.
          </p>
        </div>
        <div>
          <button 
            onClick={handleExportMarkdown}
            className="w-full sm:w-auto bg-slate-900 hover:bg-slate-800 text-white dark:bg-zinc-100 dark:hover:bg-zinc-200 dark:text-zinc-950 font-semibold px-5 py-3 rounded-xl text-xs uppercase tracking-wider shadow-sm transition-all duration-150 active:scale-[0.98] flex items-center justify-center gap-2 cursor-pointer"
          >
            <span>📥</span> Export Playbook (.md)
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* LEFT COMPONENT: Executive Summary & Operational SOP Guide */}
        <div className="lg:col-span-7 xl:col-span-8 space-y-6">
          
          {/* Executive Setup Summary */}
          <div className="bg-white dark:bg-zinc-900 border border-slate-200/90 dark:border-zinc-800 rounded-2xl shadow-sm p-6 space-y-5 transition-all">
            <div className="flex items-center space-x-3 border-b border-slate-100 dark:border-zinc-800/60 pb-3.5">
              <span className="text-lg">📊</span>
              <h2 className="text-base font-bold text-slate-855 dark:text-zinc-100">Executive Setup Summary</h2>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="p-4 rounded-xl border border-slate-100 dark:border-zinc-800/70 bg-slate-50/50 dark:bg-zinc-950/20">
                <div className="text-[10px] font-bold font-mono text-slate-400 dark:text-zinc-550 uppercase tracking-widest">Template Profile</div>
                <div className="text-sm font-extrabold text-slate-800 dark:text-zinc-100 mt-1.5 truncate font-sans" title={template.name}>
                  {template.name || "Custom Setup"}
                </div>
              </div>

              <div className="p-4 rounded-xl border border-slate-100 dark:border-zinc-800/70 bg-slate-50/50 dark:bg-zinc-950/20">
                <div className="text-[10px] font-bold font-mono text-slate-400 dark:text-zinc-550 uppercase tracking-widest">Version Baseline</div>
                <div className="text-sm font-extrabold text-slate-800 dark:text-zinc-100 mt-1.5 font-mono">
                  {template.version || "1.0.0"}
                </div>
              </div>

              <div className="p-4 rounded-xl border border-slate-100 dark:border-zinc-800/70 bg-slate-50/50 dark:bg-zinc-950/20">
                <div className="text-[10px] font-bold font-mono text-slate-400 dark:text-zinc-550 uppercase tracking-widest">Pipeline Channels</div>
                <div className="text-sm font-extrabold text-slate-800 dark:text-zinc-100 mt-1.5 font-mono">
                  {template.pipelines?.length || 0} active
                </div>
              </div>

              <div className="p-4 rounded-xl border border-slate-100 dark:border-zinc-800/70 bg-slate-50/50 dark:bg-zinc-950/20">
                <div className="text-[10px] font-bold font-mono text-slate-400 dark:text-zinc-550 uppercase tracking-widest">Custom Fields</div>
                <div className="text-sm font-extrabold text-slate-800 dark:text-zinc-100 mt-1.5 font-mono">
                  {customFieldsCount} fields
                </div>
              </div>
            </div>
          </div>

          {/* Operational SOP Guide */}
          <div className="bg-white dark:bg-zinc-900 border border-slate-200/90 dark:border-zinc-800 rounded-2xl shadow-sm p-6 space-y-6 transition-all">
            <div className="flex items-center space-x-3 border-b border-slate-100 dark:border-zinc-800/60 pb-3.5">
              <span className="text-lg">📋</span>
              <h2 className="text-base font-bold text-slate-855 dark:text-zinc-100">Operational SOP Guide</h2>
            </div>

            {template.pipelines && template.pipelines.length > 0 ? (
              <div className="space-y-6">
                {template.pipelines.map((pipe: any, index: number) => (
                  <div key={pipe.id || index} className="space-y-4 border border-slate-100 dark:border-zinc-800/75 p-5 rounded-2xl bg-slate-50/30 dark:bg-zinc-950/10">
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-bold text-slate-800 dark:text-zinc-100 flex items-center gap-2">
                        <span className="h-2 w-2 rounded-full bg-blue-500"></span>
                        Pipeline Channel: {pipe.name}
                      </h3>
                      <span className="text-[10px] font-bold font-mono bg-blue-50 text-blue-600 dark:bg-blue-950/40 dark:text-blue-400 px-2 py-0.5 rounded">
                        {pipe.stages?.length || 0} Stages
                      </span>
                    </div>

                    <div className="space-y-3 pl-3 border-l-2 border-slate-200 dark:border-zinc-800">
                      {(pipe.stages || []).map((stage: any, sIdx: number) => {
                        const days = stage.rottenDays !== undefined ? stage.rottenDays : stage.rotten_days;
                        const hasRottenDays = days !== null && days !== undefined && days !== "";
                        
                        return (
                          <div key={stage.id || sIdx} className="bg-white dark:bg-zinc-900/65 p-3 rounded-xl border border-slate-150/70 dark:border-zinc-850 flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-2xs">
                            <div className="flex items-center space-x-2">
                              <span className="text-[11px] font-bold text-slate-400 dark:text-zinc-550 font-mono">
                                Stage {sIdx + 1}:
                              </span>
                              <span className="text-xs font-bold text-slate-800 dark:text-zinc-200">
                                {stage.name}
                              </span>
                            </div>
                            
                            <div>
                              {hasRottenDays ? (
                                <span className="inline-flex items-center text-[10px] font-bold text-rose-700 bg-rose-50 border border-rose-200/80 dark:bg-rose-950/20 dark:text-rose-455 dark:border-rose-900/40 px-3 py-1 rounded-full leading-normal">
                                  🚨 CRITICAL TIMELINE: Object must progress within {days} days or it triggers an operational stagnation alert.
                                </span>
                              ) : (
                                <span className="inline-flex items-center text-[10px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200/70 dark:bg-emerald-950/15 dark:text-emerald-450 dark:border-emerald-900/30 px-3 py-1 rounded-full leading-normal">
                                  ✓ Continuous Nurture Step (No expiration decay criteria assigned).
                                </span>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-sm italic text-slate-400 text-center py-6">No pipeline structures defined in this template setup.</div>
            )}
          </div>
        </div>

        {/* RIGHT COLUMN: Data Dictionary Index & Deployment Checklist */}
        <div className="lg:col-span-5 xl:col-span-4 space-y-6">
          
          <div className="bg-white dark:bg-zinc-900 border border-slate-200/90 dark:border-zinc-800 rounded-2xl shadow-sm p-6 space-y-6 transition-all">
            
            <div className="flex items-center space-x-3 border-b border-slate-100 dark:border-zinc-800 pb-3.5">
              <span className="text-lg">🗂️</span>
              <div>
                <h2 className="text-base font-bold text-slate-855 dark:text-zinc-100">Data Dictionary</h2>
                <p className="text-[10.5px] text-slate-400 dark:text-zinc-500 font-medium mt-0.5">Deployment verification checklist</p>
              </div>
            </div>

            <div className="space-y-5">
              {categoriesList.map(cat => {
                const fields = (template.customFields || []).filter((f: any) => getCategoryName(f.scope) === cat);
                
                return (
                  <div key={cat} className="space-y-2">
                    <div className="flex items-center justify-between border-b border-slate-100 dark:border-zinc-800/80 pb-1">
                      <span className="text-xs font-bold text-slate-800 dark:text-zinc-200 tracking-tight flex items-center gap-1.5">
                        📁 {cat} Fields
                      </span>
                      <span className="text-[10px] font-mono font-bold text-slate-400 bg-slate-50 dark:bg-zinc-950 dark:text-zinc-500 px-2 py-0.5 rounded">
                        {fields.length}
                      </span>
                    </div>

                    {fields.length > 0 ? (
                      <div className="space-y-1.5">
                        {fields.map((f: any) => (
                          <div 
                            key={f.id}
                            className="group flex items-start gap-2.5 p-2 rounded-lg border border-slate-100 bg-slate-50/50 dark:border-zinc-850 dark:bg-zinc-950/20 hover:bg-slate-50 dark:hover:bg-zinc-850/40 transition-colors"
                          >
                            <input 
                              type="checkbox" 
                              className="mt-0.5 rounded border-slate-300 dark:border-zinc-700 text-blue-600 focus:ring-blue-500 h-3.5 w-3.5 shrink-0 cursor-pointer"
                            />
                            <div className="flex-1 min-w-0">
                              <div className="text-xs font-semibold text-slate-850 dark:text-zinc-200 truncate" title={f.name}>
                                {f.name}
                              </div>
                              <div className="flex items-center gap-1.5 mt-0.5">
                                <span className="text-[9px] font-mono font-bold bg-slate-100 dark:bg-zinc-855 text-slate-550 dark:text-zinc-400 px-1.5 py-0.2 rounded uppercase">
                                  {f.type || "text"}
                                </span>
                                <span className="text-[9px] font-mono text-slate-400 truncate" title={f.id}>
                                  key: {f.id}
                                </span>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-[10.5px] italic text-slate-400 dark:text-zinc-650 pl-3">
                        No custom fields configured for this category.
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}